/**
 * Principales localidades de Argentina para autocompletar la ciudad en el
 * checkout (datalist nativo). No es exhaustivo: cubre las más pobladas y
 * turísticas. El campo sigue siendo de texto libre.
 */
export const AR_CITIES: string[] = [
  "Ciudad Autónoma de Buenos Aires",
  "La Plata",
  "Mar del Plata",
  "Bahía Blanca",
  "Tandil",
  "Quilmes",
  "Lanús",
  "Lomas de Zamora",
  "Avellaneda",
  "San Isidro",
  "Tigre",
  "Vicente López",
  "Morón",
  "San Justo",
  "Pilar",
  "Escobar",
  "Luján",
  "Mercedes",
  "Junín",
  "Pergamino",
  "Olavarría",
  "Necochea",
  "Azul",
  "Zárate",
  "Campana",
  "Córdoba",
  "Villa Carlos Paz",
  "Río Cuarto",
  "Villa María",
  "San Francisco",
  "Alta Gracia",
  "Jesús María",
  "Rosario",
  "Santa Fe",
  "Rafaela",
  "Venado Tuerto",
  "Reconquista",
  "Mendoza",
  "San Rafael",
  "Godoy Cruz",
  "Maipú",
  "Luján de Cuyo",
  "San Miguel de Tucumán",
  "Yerba Buena",
  "Tafí Viejo",
  "Salta",
  "San Salvador de Jujuy",
  "San Fernando del Valle de Catamarca",
  "La Rioja",
  "Santiago del Estero",
  "La Banda",
  "Resistencia",
  "Corrientes",
  "Posadas",
  "Oberá",
  "Formosa",
  "Paraná",
  "Concordia",
  "Gualeguaychú",
  "Concepción del Uruguay",
  "Neuquén",
  "San Martín de los Andes",
  "Villa La Angostura",
  "General Roca",
  "Cipolletti",
  "San Carlos de Bariloche",
  "Viedma",
  "Puerto Madryn",
  "Comodoro Rivadavia",
  "Trelew",
  "Rawson",
  "Esquel",
  "Río Gallegos",
  "El Calafate",
  "Ushuaia",
  "Río Grande",
  "San Juan",
  "San Luis",
  "Villa Mercedes",
  "La Pampa",
  "Santa Rosa",
];
